  #  20  kubectl run n1 --image=nginx --port=80
  #  26  kubectl expose pod n1 --port=80 --target-port=80 --name=n1svc --type=NodePort
apiVersion: v1
kind: Namespace
metadata: 
  name: prod
---
apiVersion: v1
kind: Pod
metadata:
  name: n1
  labels:
    app: nginx
    env: prod 
  namespace: prod 
spec:
  containers:
  - name: nginx
    image: nginx
    ports: 
    - containerPort: 80
---
apiVersion: app/v1
kind: Deploy
metadata:
  name: n1
  labels:
    app: nginx
    env: prod 
  namespace: prod 
spec:
  replica: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: n1
      labels:
        app: nginx
        env: prod 
      namespace: prod 
    spec:
      containers:
      - name: nginx
        image: nginx
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: n1svc
  labels:
    env: prod
  namespace: prod 
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80