apiVersion: v1
kind: Namespace
metadata: 
  name: prod
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: myAWSGP2Vol1
  namespace: prod
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  iopsPerGB: "10"
  fsType: ext4
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-volume
  namespace: prod
spec:
  capacity:
    storage: 5Gi
  storageClassName: myAWSGP2Vol1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-claim
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: myAWSGP2Vol1
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  namespace: prod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: pg-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage